import type { ReactNode } from "react";
import { T } from "./i18n";

export function Section({ id, n, title, lede, children }: { id: string; n?: string; title: ReactNode; lede?: ReactNode; children: ReactNode }) {
  return (
    <section id={id} className="scroll-mt-20 border-t border-line py-16 sm:py-20">
      <div className="flex flex-col gap-3">
        <h2 className="flex flex-wrap items-baseline gap-x-3 font-display text-3xl font-bold leading-tight sm:text-4xl">
          {n && <span className="num text-xl font-normal text-muted sm:text-2xl">{n}</span>}
          <span>{title}</span>
        </h2>
        {lede && <div className="prose-k max-w-[70ch] text-ink-2">{lede}</div>}
      </div>
      <div className="mt-10 flex flex-col gap-12">{children}</div>
    </section>
  );
}

export function Sub({ id, n, title, children }: { id?: string; n: string; title: ReactNode; children?: ReactNode }) {
  return (
    <div id={id} className="flex scroll-mt-20 flex-col gap-2 border-t border-line pt-10">
      <h3 className="flex flex-wrap items-baseline gap-x-2 font-display text-2xl font-bold">
        <span className="num text-base font-normal text-muted">{n}</span>
        <span>{title}</span>
      </h3>
      {children && <div className="prose-k max-w-[70ch] text-ink-2">{children}</div>}
    </div>
  );
}

export function Card({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`min-w-0 rounded-lg border border-line bg-surface p-5 sm:p-6 ${className}`}>{children}</div>;
}

export function Pill({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "good" | "bad" | "accent" }) {
  const cls = {
    neutral: "border-line text-ink-2",
    good: "border-good/40 text-good",
    bad: "border-bad/40 text-bad",
    accent: "border-accent/40 text-accent",
  }[tone];
  return <span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-0.5 text-xs font-medium ${cls}`}>{children}</span>;
}

export function TableWrap({ children }: { children: ReactNode }) {
  return <div className="-mx-1 overflow-x-auto px-1">{children}</div>;
}

/** A numbered figure generated by `python -m kitsune.figures` from reports/: a light and a dark rendering of the same
 *  plot, of which CSS shows the one matching the page theme. Click opens the full-resolution PNG. */
export function Figure({ n, src, alt, caption }: { n: number; src: string; alt: string; caption: ReactNode }) {
  return (
    <figure className="flex min-w-0 flex-col gap-3">
      <a href={`figures/${src}.png`} target="_blank" rel="noreferrer" aria-label={`Figure ${n}, full size`} className="block">
        {/* eslint-disable-next-line @next/next/no-img-element -- static export of pre-rendered SVG */}
        <img src={`figures/${src}.svg`} alt={alt} loading="lazy" className="fig-light h-auto w-full" />
        {/* eslint-disable-next-line @next/next/no-img-element -- static export of pre-rendered SVG */}
        <img src={`figures/dark/${src}.svg`} alt="" aria-hidden loading="lazy" className="fig-dark h-auto w-full" />
      </a>
      <figcaption className="mx-auto max-w-[85ch] text-center text-sm leading-relaxed text-ink-2">
        <span className="font-semibold text-ink">
          <T en={`Figure ${n}. `} ja={`図${n}　`} mix="en" />
        </span>
        {caption}
      </figcaption>
    </figure>
  );
}

export function Ext({ href, children, className = "" }: { href: string; children: ReactNode; className?: string }) {
  return (
    <a href={href} target="_blank" rel="noreferrer" className={`text-accent underline-offset-4 hover:underline ${className}`}>
      {children}
    </a>
  );
}
